const IMAGES = {
  arrow_back: require('../assets/images/arrow_back.png'),
  avatar: require('../assets/images/avatar.png'),
  carbon_phone_voice: require('../assets/images/carbon_phone_voice.png'),
  check_box_true: require('../assets/images/check_box_true.png'),
  check_box_x: require('../assets/images/check_box_x.png'),
  cost: require('../assets/images/cost.png'),
  facebook: require('../assets/images/facebook.png'),
  field_time: require('../assets/images/field_time.png'),
  globe: require('../assets/images/globe.png'),
  heart: require('../assets/images/heart.png'),
  instgram: require('../assets/images/instgram.png'),
  location: require('../assets/images/location.png'),
  logo: require('../assets/images/logo.png'),
  marker: require('../assets/images/marker.png'),
  order_1: require('../assets/images/order_1.png'),
  order_2: require('../assets/images/order_2.png'),
  order_3: require('../assets/images/order_3.png'),
  phone_voice: require('../assets/images/phone_voice.png'),
  rectangle_1: require('../assets/images/rectangle_1.png'),
  share: require('../assets/images/share.png'),
  slide_left: require('../assets/images/slide_left.png'),
  slide_right: require('../assets/images/slide_right.png'),
  star: require('../assets/images/star.png'),
  twitter: require('../assets/images/twitter.png'),
  whatsapp: require('../assets/images/whatsapp.png'),
  youtube: require('../assets/images/youtube.png'),
  arrow_down: require('../assets/images/arrow_down.png'),
  right_arrow: require('../assets/images/right-arrow.png'),
  favorite: require('../assets/images/favorite.png'),
  close: require('../assets/images/x-mark.png'),
  write: require('../assets/images/write.png'),
};

export default IMAGES;
